before_install:
  - gem update --system
  - gem install bundler
  - gem install rake

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

addons:
  apt:
    packages:
    - libcurl4-openssl-dev


notifications:
  email: false
