remote_theme: edsandorf/jekyll-pro-theme

google_analytics: UA-154953740-01

show_navigation: true
show_search_bar: true
show_downloads: false
to_the_top: true

creator: Erlend Dancke Sandorf

e_mail: e.d.sandorf@stir.ac.uk
github_handle: edsandorf
linkedin_handle: erlend-dancke-Sandorf
twitter_handle: edsandorf
