collections:
  authors:
    output: true
  news:
    output: true
  pubs:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "pubs"
    values:
      layout: "pubs"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
permalink: /blog/:year/:month/:day/:title